### ISSUE TITLE
Setup a public build server

### ISSUE THREAD

**Issue by BenRomberg** [C4J-Team/C4J#18]
E.g. on CloudBees.

**Comment by BenRomberg** [comment]
Just had a look at CloudBees - looks like this would be alot simpler to setup using Maven (running tests etc.).

**Comment by marcphilipp** [comment]
Simpler compared to what?

**Comment by BenRomberg** [comment]
Instead of the Ant Build I'm currently using: https://github.com/C4J-Team/C4J/blob/master/c4j/build.xml - at least for running the tests with the build.

**Comment by marcphilipp** [comment]
Here are the details for the FOSS program of CloudBees: http://www.cloudbees.com/foss/foss-dev.cb

Do you want to do the registration or shall I?

**Comment by BenRomberg** [comment]
Isn't the free standard service enough? http://www.cloudbees.com/pricing-standard-services.cb

I don't want to put a logo on the page or have to twitter about them.

**Comment by marcphilipp** [comment]
The regular Jenkins instance would not be publicly accessible while the FOSS one would.

I have an account for Usus. Besides placing the logo on the homepage, i haven't done anything else. No twittering etc.

**Comment by BenRomberg** [comment]
Ok, i see. Then I would be glad if you could do the registration and setup stuff - I just started migrating the project to Maven yesterday.

**Comment by BenRomberg** [comment]
What a coincidence: http://www.heise.de/newsticker/meldung/BuildHive-CI-Plattform-fuer-GitHub-Projekte-1578920.html

Let's use BuildHive instead? Should be the same, just with integrated GitHub <-> CloudBees support!

**Comment by marcphilipp** [comment]
Sounds like a good thing to try out first!

**Comment by marcphilipp** [comment]
Right now it fails to figure out how to build it (as expected): https://buildhive.cloudbees.com/job/C4J-Team/job/C4J/1/console

We should give it another try as soon as #4 is done.

**Comment by BenRomberg** [comment]
#4 is done, I tried it again - it even detectes the modules in the parent POM, but somehow fails to launch Maven. Could you take a look?

**Comment by BenRomberg** [comment]
They fixed the bug in https://github.com/buildhive/buildhive/issues/4, leading to another problem with the JDK Version that they're using on the build server: https://github.com/buildhive/buildhive/issues/3

**Comment by BenRomberg** [comment]
Fixed the Compiler issues, build is working now: https://buildhive.cloudbees.com/job/C4J-Team/job/C4J/

Also updated the readme with a status icon of the build.

**Comment by marcphilipp** [comment]
Awesome! :-)
