### ISSUE TITLE
Register custom domain

### ISSUE THREAD

**Issue by marcphilipp** [C4J-Team/C4J#21]
Just a thought: How about registering a custom domain for C4J? The website can be hosted on GitHub as well. In addition we could have nice email addresses and use it to name the Java packages accordingly. 

Suggestion: c4j.org (if available)

**Comment by BenRomberg** [comment]
Both c4j.org and c4j.net are not available. We could go with GitHub Pages on c4j.github.com for now.

**Comment by marcphilipp** [comment]
Too bad… sounds reasonable to go with c4j.github.com as a start.
